export const CodigoDeErro = {
  REQUISICAO_INVALIDA: "REQUISICAO_INVALIDA",
  ERRO_DE_VALIDACAO: "ERRO_DE_VALIDACAO",
  NAO_AUTORIZADO: "NAO_AUTORIZADO",
  PROIBIDO: "PROIBIDO",
  NAO_ENCONTRADO: "NAO_ENCONTRADO",
  CONFLITO: "CONFLITO",
  NAO_IMPLEMENTADO: "NAO_IMPLEMENTADO",
  ERRO_INTERNO: "ERRO_INTERNO",
  TOKEN_EXPIRADO: "TOKEN_EXPIRADO",
  TOKEN_INVALIDO: "TOKEN_INVALIDO",
  VERIFICACAO_TOKEN_FALHOU: "VERIFICACAO_TOKEN_FALHOU",
  NENHUM_TOKEN_FORNECIDO: "NENHUM_TOKEN_FORNECIDO",
  CONTA_DESATIVADA: "CONTA_DESATIVADA",
  CADASTRO_EM_ANALISE: "CADASTRO_EM_ANALISE",
  CADASTRO_RECUSADO: "CADASTRO_RECUSADO",
  SOLICITACAO_JA_ENVIADA: "SOLICITACAO_JA_ENVIADA",
  SOLICITACAO_NAO_ENCONTRADA: "SOLICITACAO_NAO_ENCONTRADA",
  JA_SAO_AMIGOS: "JA_SAO_AMIGOS",
  SOLICITACAO_PARA_SI_MESMO: "SOLICITACAO_PARA_SI_MESMO",
  USUARIO_DESTINO_INDISPONIVEL: "USUARIO_DESTINO_INDISPONIVEL",
} as const;

export type ValorCodigoDeErro = (typeof CodigoDeErro)[keyof typeof CodigoDeErro];
